// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Slick Quant

// ********** THIS FILE IS AUTO-GENERATED FROM cmake/version.hpp.in **********
// ********** DO NOT EDIT THIS FILE DIRECTLY                        **********
// ********** EDIT cmake/version.hpp.in AND RE-RUN CMAKE TO UPDATE  **********

#pragma once

#define SLICK_PERFMON_VERSION_MAJOR 0
#define SLICK_PERFMON_VERSION_MINOR 1
#define SLICK_PERFMON_VERSION_PATCH 0
#define SLICK_PERFMON_VERSION \
    "0.1.0"
